export default {
  "data": [
    {
      "name": "Aircraft Cleaning",
      "fullName": "Aircraft Cleaning - SI001",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 1,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI001",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "AC Unit",
      "fullName": "AC Unit - SI002",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        },
        {
          "name": "remark",
          "type": "input",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 2,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 2,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI002",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Airstart Unit",
      "fullName": "Airstart Unit - SI003",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        },
        {
          "name": "remark",
          "type": "input",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 2,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 3,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI003",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Crew Services - Transport",
      "fullName": "Crew Services - Transport - SI022",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 20,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI022",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Crew Stairs Unit",
      "fullName": "Crew Stairs Unit - SI023",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 21,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI023",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "GPU Service",
      "fullName": "GPU Service - SI034",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": 1,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "Start",
          "type": "fullDate",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 3,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        },
        {
          "name": "End",
          "type": "fullDate",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 4,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 32,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI034",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Lavatory Service",
      "fullName": "Lavatory Service - SI042",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 40,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI042",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Pallet Transport",
      "fullName": "Pallet Transport - SI048",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 46,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI048",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Pushback Service",
      "fullName": "Pushback Service - SI051",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "quantity",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 11,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 49,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI051",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Regulated Garbage",
      "fullName": "Regulated Garbage - SI057",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 55,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI057",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Transfers/Line Haul/Drayage Ramp",
      "fullName": "Transfers/Line Haul/Drayage Ramp - SI070",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 68,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI070",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Water Service",
      "fullName": "Water Service - SI075",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 73,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI075",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Ramp Marshalling",
      "fullName": "Ramp Marshalling - SI107",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 83,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI107",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Aircraft Parking",
      "fullName": "Aircraft Parking - SI008",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": 1,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "Start",
          "type": "fullDate",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 3,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        },
        {
          "name": "End",
          "type": "fullDate",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 4,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 101,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI008",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Towing Service",
      "fullName": "Towing Service - SI126",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 126,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI126",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Extended Towing Service",
      "fullName": "Extended Towing Service - SI138",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 138,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": "SI138",
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Loadmaster",
      "fullName": "Loadmaster - ",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "quantity",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 11,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 144,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": null,
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Forklift",
      "fullName": "Forklift - ",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 4,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        },
        {
          "name": "remark",
          "type": "input",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 2,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 145,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": null,
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    },
    {
      "name": "Loader",
      "fullName": "Loader - ",
      "label": null,
      "categoryId": 1,
      "status": true,
      "type": null,
      "measureUnitId": 10,
      "measureUnit": null,
      "workdayTransactions": null,
      "category": {
        "name": "Services",
        "parentId": null,
        "id": 1,
        "createdAt": null,
        "updatedAt": null,
        "deletedAt": null,
        "createdBy": null,
        "updatedBy": null,
        "deletedBy": null,
        "externalId": null,
        "options": null,
        "crudPermissions": {},
        "defaultInclude": "",
        "searchableFields": "",
        "fileFormats": null
      },
      "attributes": [
        {
          "name": "",
          "type": "quantity",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 1,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        },
        {
          "name": "remark",
          "type": "input",
          "required": false,
          "defaultInclude": "values",
          "values": [],
          "id": 2,
          "createdAt": null,
          "updatedAt": null,
          "deletedAt": null,
          "createdBy": null,
          "updatedBy": null,
          "deletedBy": null,
          "externalId": null,
          "options": null,
          "crudPermissions": {},
          "searchableFields": "",
          "fileFormats": null
        }
      ],
      "id": 147,
      "createdAt": null,
      "updatedAt": null,
      "deletedAt": null,
      "createdBy": null,
      "updatedBy": null,
      "deletedBy": null,
      "externalId": null,
      "options": { "options": "{}" },
      "dynamicParameters": {},
      "crudPermissions": {},
      "defaultInclude": "",
      "searchableFields": "",
      "fileFormats": null
    }
  ]
}
