export const form = {
    serviceDate: null,
    aircraftType: null,
    fuelTicket: null,
    tailNumber: null,
    prist: null,
    jetA: null,
    diesel: null,
    gas: null,
    miscellaneous: null,
    overnightParking: null,
    callOutSecond: null,
    spirit: null,
    compass: null,
    defuelFee: null,
    endeavor: null,
    expressJet: null,
    goJet: null,
    gaugeFueling: null,
    regular: null,
    shuttle: null,
    skyWest: null,
    delta: null,
    republic: null,
    atlanticSoutheastAirlines: null,
}